<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // Drop the PostgreSQL check constraint left over from the original enum definition.
        // The constraint name is auto-generated by PostgreSQL as "{table}_{column}_check".
        DB::statement('ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_type_check');

        // Also drop status check constraint if it exists
        DB::statement('ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_status_check');
    }

    public function down(): void
    {
        // Optionally re-add the original constraints
        DB::statement("ALTER TABLE transactions ADD CONSTRAINT transactions_type_check CHECK (type IN ('IN','OUT','TRANSFER','RESERVE'))");
    }
};
